import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [subReddit, setSubReddit] = useState("");
  const [redditData, setRedditData] = useState([]);

  // fetch data based on subreddit
  function fetchNewPage() {
    const after =
      redditData.length > 0 ? redditData[redditData.length - 1].name : "";
    console.log({ after });
    return fetch(
      `https://www.reddit.com/r/${subReddit}.json?after=${after}&limit=25`
    )
      .then((res) => res.json())
      .then(({ data }) =>
        data.children.map(({ data: post }) => ({
          id: post.id,
          name: post.name,
          title: post.title,
          url: post.url,
        }))
      )
      .then((data) => {
        setRedditData(data);
      });
  }

  function handleSubredditSubmit(e) {
    e.preventDefault();
    fetchNewPage();
  }

  function subRedditChange(e) {
    setSubReddit(e.target.value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Reddit Lite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Reddit Lite</h1>

        <form onSubmit={handleSubredditSubmit}>
          <label>
            Subreddit
            <input type="text" value={subReddit} onChange={subRedditChange} />
          </label>
          <input type="submit" value="Load" />
        </form>

        {redditData && redditData.length > 0 && (
          <div>
            <ol>
              {redditData.map((item) => (
                <li key={item.id}>
                  <a target="_blank" rel="noreferrer" href={item.url}>
                    {item.title}
                  </a>
                </li>
              ))}
            </ol>
            <button onClick={fetchNewPage}>Next</button>
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
